### ISSUE TITLE
Mediawiki "resulting LocalSettings.php"

### ISSUE THREAD

**Issue by dogweather** [nickstenning/dockerfiles#10]
Hi, I'm trying to get the mediawiki up and running, but I don't see this file, mentioned in the README created anywhere. And then the README says to place this on the "host". I.e., not inside the container. Is this correct?

**Comment by nickstenning** [comment]
Ah, the idea would be to use `docker cp` to get the `LocalSettings.php` generated by the installer out of the config container.

**Comment by nickstenning** [comment]
Oops. I've just checked over this again and no, it's not a matter of using `docker cp` -- the MediaWiki installed generates a `LocalSettings.php` that your browser will automatically download at the end of installation.
