### ISSUE TITLE
Feature request for mediawiki image

### ISSUE THREAD

**Issue by pedrox** [nickstenning/dockerfiles#13]
Things I had to install on top that would be nice to include:
* Install PHP mail support: packages php-mail and php-net-smtp
* Setup friendly URLs: http://www.mediawiki.org/wiki/Manual:Short_URL/wiki/Page_title_--_nginx_rewrite--root_access (or just provide the nginx configuration file in a volume)

Thanks for providing the mediawiki image!

**Comment by nickstenning** [comment]
The latest version of the image (`latest` or `0.26.3`) includes `php-mail` and `php-net-smtp`! Thanks for the suggestion.

While friendly URLs would be nice, it would be a backwards-incompatible change for this container, so I've settled for making it possible to drop `*.conf` files in the `nginx/`  directory of the data volume.

Thanks again for your feedback. Hope the image continues to be useful!

**Comment by pedrox** [comment]
Great! Thank you.
